 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  artpedia_bw: # name of the dataset builder
    dataset_card: dataset_card/artpedia.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: path/artpedia_train_coco1.json
        val:
          storage:  path/artpedia_val_coco_new.json
        test:
          storage: path/artpedia_test_coco_new.json
      images:
        storage: path/images/bw
